language: c

compiler:
  - clang

addons:
  apt:
    packages:
    - cmake
    - check
    - libudev-dev
    - ninja-build
    - pkg-config

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -GNinja ..

script:
  - ninja
  - ctestt --output-on-failure
